#docker-compose up -d
version: '3'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: container_jenkins_2
    ports:
      - "5000:50000"
      - "8080:8080"

    volumes:
      - jenkins_home:/var/jenkins_home
      - jenkins_config:/var/jenkins_config

volumes:
  jenkins_home:
  jenkins_config:
